# Generated by Django 5.1.5 on 2025-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagenP', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
