# Generated by Django 5.1.5 on 2025-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
                ('apellidoC', models.CharField(max_length=50)),
                ('numeroTelefonico', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.BinaryField()),
            ],
        ),
    ]
