# Generated by Django 5.1.5 on 2025-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
